# Generated by Django 3.2.8 on 2021-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_sport', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
    ]
